Ecommerce/Controllers/CustomersController.cs
using Ecommerce.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        public ActionResult Index()
        {
            var customersList = CustomerRepository.GetCustomers();

            return View(customersList);
        }

        // GET: Customers/Details/5
        public ActionResult Details(int id)
        {
            var customerDetails = CustomerRepository.GetCustomerById(id);

            return View(customerDetails);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {

            try
            {
                CustomerRepository.Insert(customer);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int id)
        {
            var customerDetails = CustomerRepository.GetCustomerById(id);

            return View(customerDetails);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Customer customer)
        {
            var customerDetails = CustomerRepository.GetCustomerById(id);

            try
            {
                CustomerRepository.Update(customer);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int id)
        {
            var customerDetails = CustomerRepository.GetCustomerById(id);

            return View(customerDetails);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var customerDetails = CustomerRepository.GetCustomerById(id);

            try
            {
                CustomerRepository.Remove(customerDetails);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Ecommerce/Controllers/OrdersController.cs
using System.Collections.Generic;
using Ecommerce.Models;
using Ecommerce.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace Ecommerce.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Orders
        public ActionResult Index()
        {
            var list = OrderRepository.GetOrders();

            foreach (var item in list)
            {
                item.Customer = CustomerRepository.GetCustomerById(item.CustomerId);
            }

            return View(list);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int id)
        {
            return View(OrderRepository.GetOrderById(id));
        }

        // GET: Orders/Create
        [HttpGet]
        public ActionResult Create()
        {
            var model = new Order();

            //ViewBag.Customers = new SelectList(CustomerRepository.GetCustomers(), "Id", "FullName");
            model.Customers =  CustomerRepository.GetCustomers();
            model.CartDetails = HttpContext.Session.Get<List<Cart>>("cartV");

            //var productRepository = new ProductRepository();
            //model.Products = ProductRepository.GetProducts();

            //var a = HttpContext.Session.Get<List<OrderDetails>>("cart");
            //ViewBag.Products = new SelectList (a, "Id", "Name");

            return View(model);
        }

        // POST: Orders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order model)
        {
            model.CartDetails = HttpContext.Session.Get<List<Cart>>("cartV");

            foreach (var detail in model.CartDetails)
            {
                model.TotalPrice += detail.StockControl.Product.RetailPrice * detail.Quantity;
            }

            OrderRepository.Insert(model);

            PaymentCardRepository.Insert(model.Payment);

            return RedirectToAction(nameof(Index));
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int id)
        {
            var orderDetails = OrderRepository.GetOrderById(id);

            return View(orderDetails);
        }

        // POST: Orders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Order order)
        {
            try
            {
                OrderRepository.Update(order);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int id)
        {
            var orderDetails = OrderRepository.GetOrderById(id);

            return View(orderDetails);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var orderDetails = OrderRepository.GetOrderById(id);

            try
            {
                OrderRepository.Remove(orderDetails);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        
    }
}

Ecommerce/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using Ecommerce.Logic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using Newtonsoft.Json;

namespace Ecommerce.Controllers
{
    public class ProductsController : Controller
    {
        public ProductsController()
        {
        }
        // GET: Products
        public ActionResult Index()
        {
            var products = ProductLogic.GetProducts();

            foreach (var item in products)
            {
                item.Category = CategoryRepository.GetCategoryById(item.CategoryId);
            }

            return View(products);
        }

        // GET: Products/Details/5
        public ActionResult Details(int id)
        {
            var product = ProductLogic.GetProductById(id);

            return View(product);
        }

        public IActionResult Buy(int id)
        {
            var cart = HttpContext.Session.Get<List<OrderDetail>>("cart");
            if(cart == null)
            {
                cart = new List<OrderDetail>();
                var orderDetaili = new OrderDetail()
                {
                    Product = ProductRepository.GetProductById(id),
                    Quantity = 1
                };
                cart.Add(orderDetaili);
                HttpContext.Session.Set<List<OrderDetail>>("cart", cart);
            }
            else
            {
                foreach(var item in cart)
                {
                    if(item.Product.Id == id)
                    {
                        item.Quantity++;
                    }
                }
                HttpContext.Session.Set<List<OrderDetail>>("cart", cart);
            }
            return RedirectToAction("Index");
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.Categories = CategoryRepository.GetCategories();
            
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            try
            {
                ProductLogic.Insert(product);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return RedirectToAction(nameof(Create));
            }
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int id)
        {
            var product = ProductLogic.GetProductById(id);

            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Product product)
        {
            try
            {
                ProductLogic.Update(product);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int id)
        {
            var product = ProductLogic.GetProductById(id);

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var product = ProductRepository.GetProductById(id);

            try
            {
                ProductLogic.Remove(product);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }

    public static class SessionExtensions
    {
        public static void Set<T>(this ISession session, string key, T value)
        {
            session.SetString(key, JsonConvert.SerializeObject(value, Formatting.None,
                        new JsonSerializerSettings()
                        {
                            ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                        }));
        }
        public static T Get<T>(this ISession session, string key)
        {
            var value = session.GetString(key);
            return value == null ? default(T) :
                                  JsonConvert.DeserializeObject<T>(value);
        }
    }
}

Ecommerce/Controllers/StocksController.cs
using Ecommerce.Models;
using Ecommerce.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Ecommerce.Controllers
{
    public class StocksController : Controller
    {
        // GET: Stocks
        public ActionResult Index()
        {
            var stocks = StockRepository.GetStocks();
            var stockIds = stocks.Select(i => i.Id).ToList();
            var stockControls = StockControlRepository.GetStockControls();

            var categoryStocks = stockControls.Where(t => stockIds.Contains(t.StockId));

            foreach (var stock in stocks)
            {
                var stockControlId = StockControlRepository.GetStockControlById(stock.Id);

                if (stock.StockControls == null)
                {
                    stock.StockControls = new List<StockControl>();
                }

                if (stockControlId.StockId == stock.Id)
                {
                    stock.StockControls.AddRange(categoryStocks);
                }
            }

            return View(stocks);
        }

        // GET: Stocks/Details/5
        public ActionResult Details(int id)
        {
            var stock = StockRepository.GetStockById(id);

            return View(stock);
        }

        // GET: Stocks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stocks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Stock stock)
        {
            try
            {
                StockRepository.Insert(stock);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Stocks/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Stocks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Stock stock)
        {
            try
            {
                StockRepository.Update(stock);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Stocks/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Stocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var stock = StockRepository.GetStockById(id);

            try
            {
                StockRepository.Remove(stock);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Ecommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-between">
                    <ul class="navbar-nav mr-auto flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stocks" asp-action="Index">Stock</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PaymentCards" asp-action="Index">Cards</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="/Carts">
                                <i 
                                    style="font-size:1.7em;color:orange;padding-top: 8px;margin-right: 25px;" 
                                    class="fa fa-shopping-cart" aria-hidden="true"></i>
                            </a>
                        </li>
                        <!--
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                            -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Ecommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>